org.joget.marketplace.encryptedfiledatalistformatter.pluginLabel=Encrypted File Datalist Formatter
org.joget.marketplace.encryptedfiledatalistformatter.pluginDesc=To format the column value as attachment download link with runtime decryption.
org.joget.marketplace.encryptedfiledatalistformatter.edit=Configure Encrypted File Datalist Formatter
org.joget.marketplace.encryptedfiledatalistformatter.formDefId=Form
org.joget.marketplace.encryptedfiledatalistformatter.encryptionKey=Encryption Key / Hash Variable
org.joget.marketplace.encryptedfiledatalistformatter.encryptionKey.desc=Enter an encryption key directly or use an App Variable hash variable.
org.joget.marketplace.encryptedfiledatalistformatter.downloadAsAttachment=Download as Attachment
